<div class="row">
    <div class="ui twelve wide computer column">
        <div class="typo-section-sq bottom-big">

            <div class="typo-section-header-sq">
                <h2 class="text-align-left-sq structures-head">Top Cities to visit</h2>
            </div>

            <div class="magic-grid category-sq special-sq hover-center">

                <!-- item-->
                <div class="item">
                    <div class="item-inner">

                        <!-- image container -->
                        <div class="image-sq">
                            <div class="image-wrapper">
                                <div class="image-inner">
                                    <img class="image-sq" src="<?php $this->getBaseUrl()?>media/wysiwyg/structures/str_1.jpg " alt="">
                                </div>
                            </div>
                        </div>

                        <!-- typography container-->
                        <a href="listing_page.html" class="typo-sq">
                            <span class="typo-whitespace"></span>
                            <p class="typo-label-sq" data-label-before="Greece" data-label-after="Book a home in"></p>
                            <p class="typo-title-sq">Lefkada</p>
                        </a>

                    </div>
                </div>

                <!-- item-->
                <div class="item">
                    <div class="item-inner">

                        <!-- image container -->
                        <div class="image-sq">
                            <div class="image-wrapper">
                                <div class="image-inner">
                                    <img class="image-sq" src="<?php $this->getBaseUrl()?>media/wysiwyg/structures/str_4.jpg " alt="">
                                </div>
                            </div>
                        </div>

                        <!-- typography container-->
                        <a href="listing_page.html" class="typo-sq">
                            <span class="typo-whitespace"></span>
                            <p class="typo-label-sq" data-label-before="Netherlands" data-label-after="Book a home in"></p>
                            <p class="typo-title-sq">Amsterdam</p>
                        </a>

                    </div>
                </div>

                <!-- item-->
                <div class="item">
                    <div class="item-inner">

                        <!-- image container -->
                        <div class="image-sq">
                            <div class="image-wrapper">
                                <div class="image-inner">
                                    <img class="image-sq" src="<?php $this->getBaseUrl()?>media/wysiwyg/structures/str_2.jpg" alt="">
                                </div>
                            </div>
                        </div>

                        <!-- typography container-->
                        <a href="listing_page.html" class="typo-sq">
                            <span class="typo-whitespace"></span>
                            <p class="typo-label-sq" data-label-before="France" data-label-after="Book a home in"></p>
                            <p class="typo-title-sq">Paris</p>
                        </a>

                    </div>
                </div>

                <!-- item-->
                <div class="item">
                    <div class="item-inner">

                        <!-- image container -->
                        <div class="image-sq">
                            <div class="image-wrapper">
                                <div class="image-inner">
                                    <img class="image-sq" src="<?php $this->getBaseUrl()?>media/wysiwyg/structures/str_3.jpg " alt="">
                                </div>
                            </div>
                        </div>

                        <!-- typography container-->
                        <a href="listing_page.html" class="typo-sq">
                            <span class="typo-whitespace"></span>
                            <p class="typo-label-sq" data-label-before="Czech" data-label-after="Book a home in"></p>
                            <p class="typo-title-sq">Prague</p>
                        </a>

                    </div>
                </div>

                <!-- item-->
                <div class="item">
                    <div class="item-inner">

                        <!-- image container -->
                        <div class="image-sq">
                            <div class="image-wrapper">
                                <div class="image-inner">
                                    <img class="image-sq" src="<?php $this->getBaseUrl()?>media/wysiwyg/structures/str_1.jpg " alt="">
                                </div>
                            </div>
                        </div>

                        <!-- typography container-->
                        <a href="listing_page.html" class="typo-sq">
                            <span class="typo-whitespace"></span>
                            <p class="typo-label-sq" data-label-before="Greece" data-label-after="Book a home in"></p>
                            <p class="typo-title-sq">Lefkada</p>
                        </a>

                    </div>
                </div>

                <!-- item-->
                <div class="item">
                    <div class="item-inner">

                        <!-- image container -->
                        <div class="image-sq">
                            <div class="image-wrapper">
                                <div class="image-inner">
                                    <img class="image-sq" src="<?php $this->getBaseUrl()?>media/wysiwyg/structures/str_4.jpg " alt="">
                                </div>
                            </div>
                        </div>

                        <!-- typography container-->
                        <a href="listing_page.html" class="typo-sq">
                            <span class="typo-whitespace"></span>
                            <p class="typo-label-sq" data-label-before="Netherlands" data-label-after="Book a home in"></p>
                            <p class="typo-title-sq">Amsterdam</p>
                        </a>

                    </div>
                </div>

                <!-- item-->
                <div class="item">
                    <div class="item-inner">

                        <!-- image container -->
                        <div class="image-sq">
                            <div class="image-wrapper">
                                <div class="image-inner">
                                    <img class="image-sq" src="<?php $this->getBaseUrl()?>media/wysiwyg/structures/str_2.jpg" alt="">
                                </div>
                            </div>
                        </div>

                        <!-- typography container-->
                        <a href="listing_page.html" class="typo-sq">
                            <span class="typo-whitespace"></span>
                            <p class="typo-label-sq" data-label-before="France" data-label-after="Book a home in"></p>
                            <p class="typo-title-sq">Paris</p>
                        </a>

                    </div>
                </div>

            </div>

            <a class="more-trigger" data-more="See All" href="listing_page.html">
                <i class="icon icon-arrow-down-122"></i>
            </a>
        </div>

    </div>



</div>