
<style type="text/css">

    .circle-text {
        max-width: 460px;
    }

    .circle-text:after {
        content: "";
        display: block;
        width: 100%;
        height:0;
        padding-bottom: 96%;
        border: 15px solid #a8a8a8;
        -moz-border-radius: 50%;
        -webkit-border-radius: 50%;
        border-radius: 50%;
        background: url(http://localhost/mycircle2/media/wysiwyg/banners/parco1.jpg);
        background-repeat: no-repeat;
        background-position: center top;
        background-size: 100%;
        /*background: url("http://localhost/mycircle2/media/wysiwyg/banners/parco1.jpg") no-repeat -30px -50px no-scroll;*/
    }
    .circle-text .image-inner {
        float:left;
        width:100%;
        line-height:1em;
        margin-top:-0.5em;
        text-align:center;
        color:white;
    }

    .white-section.no-padding {
        padding: 0;
    }


    .circle-text-top {
        margin-right: -15%;
    }
    .circle-text-bottom {
        margin-left: -15%;
    }


    .circle__inner {
        position: relative;
        top: 215px;
        bottom: 0;
        left: 22px;
        width: 100%;
        height: 100%;
    }

    .circle__wrapper {
        display: table;
        width: 100%;
        height: 100%;
    }

    .circle__content {
        padding: 1em 0 0.2em;
        vertical-align: middle;
        position: absolute;
        top: 23%;
        left: 20%;

    }

    .circle__content .circle-separator {
        padding: 0;
        margin: 3px;
    }

    .circle__content .title-row {
         font-size: 26px;
         font-weight: bold;
        text-align: center;
    }

    .circle__content .date-row {
        text-align: center;
        margin-top: 5px;
    }

    .countdown-row {
        margin-top: 10px;
    }

    .countdown-row .countdown-item {
        background-color: #ce6c87;
        -moz-border-radius: 50%;
        -webkit-border-radius: 50%;
        border-radius: 50%;
        padding: 5px;
        color: #ffffff;
        font-weight: bold;
        margin: 7px;

    }

    .countdown-row {

        text-align: center;
        margin-left: 9%;

    }

    .countdown-row .countdown-container {
        float: left;
    }

    .countdown-label {
        font-size: 0.7em;
    }

    .circle__content .price-box {
        text-align: center;
        font-size: 20px;
        font-weight: bold;
    }


    .circle__content .price-box .separator-price {
        color: #a8a8a8;
        font-weight: lighter;
    }


    .circle__content .price-box .old-price {
        color: #a8a8a8;
    }

    .circle__content .price-box .new-price {
        color: #ee265b;
    }
    .circle__content .join-item img {
        width: 20%;
        margin: 1% auto;
    }






</style>
<div class="row">
    <div class="ui column">
        <div class="white-section shadow-sq no-padding">

            <div class="sq-slick carousel-sq center-sq spread-sq" data-center-mode="false" data-center-padding="0px" data-desktop-center-padding="0px" data-show-slides="3" data-scroll-slides="3" data-desktop-show-slides="3" data-desktop-scroll-slides="3" data-tablet-show-slides="2" data-tablet-scroll-slides="2" data-mobile-show-slides="1" data-mobile-scroll-slides="1" data-tablet-center-padding="0px" data-mobile-center-padding="40px">

                <?php for($i=0;$i<=10;$i++) : ?>
                    <div>

                        <div class="circle-text-container">
                            <div class="circle-text circle-text-top">
                                <div class="circle__inner">
                                    <div class="circle__wrapper">
                                        <div class="circle__content circle-separator">
                                            <div class="circle-main-details">
                                                <div class="title-row">Mirbilandia</div>
                                                <div class="date-row">dal 12.11.2017 al 13.11.2017</div>
                                                <div class="countdown-row">
                                                    <div class="countdown-container">
                                                        <span class="countdown-item">20</span>
                                                        <br />
                                                        <span class="countdown-label">giorni</span>
                                                    </div>
                                                    <div class="countdown-container">
                                                        <span class="countdown-item">10</span>
                                                        <br />
                                                        <span class="countdown-label">ore</span>
                                                    </div>
                                                    <div class="countdown-container">
                                                        <span class="countdown-item">30</span>
                                                        <br />
                                                        <span class="countdown-label">minuti</span>
                                                    </div>
                                                    <div class="countdown-container">
                                                        <span class="countdown-item">50</span>
                                                        <br />
                                                        <span class="countdown-label">secondi</span>
                                                    </div>
                                                </div>
                                            </div>
                                            <hr class="circle-separator" />
                                            <div class="price-box">
                                                <span class="old-price">295,00 €</span>
                                                <span class="separator-price">|</span>
                                                <span class="new-price">195,00 €</span>
                                            </div>
                                            <div class="join-box">
                                                <span class="join-item">
                                                    <a href="">
                                                        <img src="<?php echo $this->getSkinUrl() ?>images/join.png" alt="">
                                                    </a>

                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="circle-text circle-text-bottom">
                                <div class="circle__inner">
                                    <div class="circle__wrapper">
                                        <div class="circle__content circle-separator">
                                            <div class="circle-main-details">
                                                <div class="title-row">Mirbilandia</div>
                                                <div class="date-row">dal 12.11.2017 al 13.11.2017</div>
                                                <div class="countdown-row">
                                                    <div class="countdown-container">
                                                        <span class="countdown-item">20</span>
                                                        <br />
                                                        <span class="countdown-label">giorni</span>
                                                    </div>
                                                    <div class="countdown-container">
                                                        <span class="countdown-item">10</span>
                                                        <br />
                                                        <span class="countdown-label">ore</span>
                                                    </div>
                                                    <div class="countdown-container">
                                                        <span class="countdown-item">30</span>
                                                        <br />
                                                        <span class="countdown-label">minuti</span>
                                                    </div>
                                                    <div class="countdown-container">
                                                        <span class="countdown-item">50</span>
                                                        <br />
                                                        <span class="countdown-label">secondi</span>
                                                    </div>
                                                </div>
                                            </div>
                                            <hr class="circle-separator" />
                                            <div class="price-box">
                                                <span class="old-price">295,00 €</span>
                                                <span class="separator-price">|</span>
                                                <span class="new-price">195,00 €</span>
                                            </div>
                                            <div class="join-box">
                                                <span class="join-item">
                                                    <a href="">
                                                        <img src="<?php echo $this->getSkinUrl() ?>images/join.png" alt="">
                                                    </a>

                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>

                <?php endfor; ?>

            </div>


        </div>
    </div>
</div>
