
<style type="text/css">



</style>
<div class="row">

    <div class="typo-section-header-sq structures-head">
        <h2 class="text-align-left-sq structures-head">sconti sicuri</h2>
    </div>


    <div class="ui grid container bottom-big">


                <?php for($i=0;$i<=10;$i++) : ?>
                    <div class="twelve wide mobile six wide tablet four wide computer two wide widescreen three wide large screen column circle-promo-wrapper">
                        <div class="circle-promo-container">
                            <div class="circle-promo">
                                <div class="circle_promo_inner">
                                    <div class="circle_promo_wrapper">
                                        <div class="circle_promo_content circle-separator">
                                            <div class="circle-main-details">
                                                <div class="title-row">Mirbilandia</div>
                                            </div>
                                            <hr class="circle-separator" />
                                            <div class="price-box">
                                                <p class="old-price">295,00 €</p>
                                                <p class="new-price">195,00 €</p>
                                            </div>
                                            <div class="join-box">
                                                <span class="join-item">
                                                    <a href="">
                                                        <img src="<?php echo $this->getSkinUrl() ?>images/join.png" alt="">
                                                    </a>

                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endfor; ?>

            <div class="latest-action">
                <a class="button-sq small-sq" tabindex="0">mostra tutti</a>
            </div>

    </div>
</div>
