
<style type="text/css">

    .circle-promo-wrapper {
        margin-bottom: 20px;
        margin-top: 20px;
    }

    .circle-promo:after {
        content: "";
        display: block;
        width: 100%;
        height:0;
        padding-bottom: 96%;
        border: 8px solid #ed255b;
        -moz-border-radius: 50%;
        -webkit-border-radius: 50%;
        border-radius: 50%;
        background: url(http://localhost/mycircle2/media/wysiwyg/banners/parco1.jpg);
        background-repeat: no-repeat;
        background-position: center top;
        background-size: 100%;
        /*background: url("http://localhost/mycircle2/media/wysiwyg/banners/parco1.jpg") no-repeat -30px -50px no-scroll;*/
    }
    .circle-promo .image-inner {
        float:left;
        width:100%;
        line-height:1em;
        margin-top:-0.5em;
        text-align:center;
        color:white;
    }

    .white-section.no-padding {
        padding: 0;
    }


    .circle-promo-top {
        margin-right: -15%;
    }
    .circle-promo-bottom {
        margin-left: -15%;
    }


    .circle_promo_inner {
        position: relative;
        top: 165px;
        bottom: 0;
        left: 26px;
        width: 100%;
        height: 100%;
    }

    .circle_promo_wrapper {
        display: table;
        width: 100%;
        height: 100%;
    }

    .circle_promo_content {
        padding: 1em 0 0.2em;
        vertical-align: middle;
        position: absolute;
        top: 23%;
        left: 20%;

    }

    .circle_promo_content .circle-separator {
        padding: 0;
        margin: 11px 0 4px 0px;
    }

    .circle_promo_content .title-row {
         font-size: 26px;
         font-weight: bold;
        text-align: center;
    }

    .circle_promo_content .date-row {
        text-align: center;
        margin-top: 5px;
    }

    .countdown-row {
        margin-top: 10px;
    }

    .countdown-row .countdown-item {
        background-color: #ce6c87;
        -moz-border-radius: 50%;
        -webkit-border-radius: 50%;
        border-radius: 50%;
        padding: 5px;
        color: #ffffff;
        font-weight: bold;
        margin: 7px;

    }

    .countdown-row {

        text-align: center;
        margin-left: 9%;

    }

    .countdown-row .countdown-container {
        float: left;
    }

    .countdown-label {
        font-size: 0.7em;
    }

    .circle_promo_content .price-box {
        text-align: center;
        font-size: 40px;
        font-weight: bold;
    }


    .circle_promo_content .price-box .separator-price {
        color: #a8a8a8;
        font-weight: lighter;
    }


    .circle_promo_content .price-box .old-price {
        font-size: 25px;
        color: #a8a8a8;
        text-decoration: line-through;
        padding: 0;
        margin: 0;
        line-height: 18px;
    }

    .circle_promo_content .price-box .new-price {
        color: #ee265b;
    }

    .circle_promo_content .join-box {
        margin: auto;
    }

    .circle_promo_content .join-item img {
        width: 25%;
        margin: 3% 0 0 40%;
    }

    .latest-action {
        padding: 4% 0 0 0;
        text-align: center;
        width: 100%;
        padding: 4% 0 4% 0;
    }

    .typo-section-sq .structures-head {

        padding-right: 4%;
        width: 100%;

    }

</style>
<div class="row">

    <div class="typo-section-header-sq structures-head">
        <h2 class="text-align-left-sq structures-head">Top Cities to visit</h2>
    </div>


    <div class="ui grid container bottom-big">


                <?php for($i=0;$i<=10;$i++) : ?>
                    <div class="twelve wide mobile six wide tablet four wide computer three wide large screen column circle-promo-wrapper">
                        <div class="circle-promo-container">
                            <div class="circle-promo">
                                <div class="circle_promo_inner">
                                    <div class="circle_promo_wrapper">
                                        <div class="circle_promo_content circle-separator">
                                            <div class="circle-main-details">
                                                <div class="title-row">Mirbilandia</div>
                                            </div>
                                            <hr class="circle-separator" />
                                            <div class="price-box">
                                                <p class="old-price">295,00 €</p>
                                                <p class="new-price">195,00 €</p>
                                            </div>
                                            <div class="join-box">
                                                <span class="join-item">
                                                    <a href="">
                                                        <img src="<?php echo $this->getSkinUrl() ?>images/join.png" alt="">
                                                    </a>

                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endfor; ?>

            <div class="latest-action">
                <a class="button-sq small-sq" tabindex="0">mostra tutti</a>
            </div>

    </div>
</div>
